#if defined(BOOST_VMD_TEST_GENERAL_HEADER)
#include <boost/vmd/vmd.hpp>
#else
#include <boost/vmd/equal.hpp>
#include <boost/vmd/not_equal.hpp>
#endif
#include <boost/detail/lightweight_test.hpp>

int main()
  {
  
#if BOOST_PP_VARIADICS
  
  BOOST_TEST(BOOST_VMD_EQUAL(BOOST_VMD_TYPE_LIST,BOOST_VMD_TYPE_LIST,BOOST_VMD_TYPE_TYPE));
  BOOST_TEST(BOOST_VMD_EQUAL(BOOST_VMD_TYPE_SEQ,BOOST_VMD_TYPE_SEQ,BOOST_VMD_TYPE_TYPE));
  BOOST_TEST(BOOST_VMD_EQUAL(BOOST_VMD_TYPE_SEQ,BOOST_VMD_TYPE_SEQ,BOOST_VMD_TYPE_IDENTIFIER));
  BOOST_TEST(BOOST_VMD_NOT_EQUAL(BOOST_VMD_TYPE_EMPTY,BOOST_VMD_TYPE_SEQUENCE,BOOST_VMD_TYPE_TYPE));
  BOOST_TEST(BOOST_VMD_NOT_EQUAL(BOOST_VMD_TYPE_TUPLE,NOT_TYPE,BOOST_VMD_TYPE_TYPE));
  BOOST_TEST(BOOST_VMD_NOT_EQUAL(BOOST_VMD_TYPE_TYPE,(3),BOOST_VMD_TYPE_TYPE));
  
#else

BOOST_ERROR("No variadic macro support");
  
#endif

  return boost::report_errors();
  
  }
