#if !defined(BOOST_VMD_DETAIL_COMP_EQUAL_8_HPP)
#define BOOST_VMD_DETAIL_COMP_EQUAL_8_HPP

#include <boost/vmd/detail/recurse/comp_equal/comp_equal_headers.hpp>

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_ARRAY(elf,els) \
	BOOST_VMD_DETAIL_DATA_EQUAL_8(elf,els,BOOST_PP_ARRAY_SIZE,BOOST_PP_ARRAY_ELEM) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_ARRAY_D(d,elf,els) \
	BOOST_VMD_DETAIL_DATA_EQUAL_8_D(d,elf,els,BOOST_PP_ARRAY_SIZE,BOOST_PP_ARRAY_ELEM) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_SEQ(elf,els) \
	BOOST_VMD_DETAIL_DATA_EQUAL_8(elf,els,BOOST_PP_SEQ_SIZE,BOOST_PP_SEQ_ELEM) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_SEQ_D(d,elf,els) \
	BOOST_VMD_DETAIL_DATA_EQUAL_8_D(d,elf,els,BOOST_PP_SEQ_SIZE,BOOST_PP_SEQ_ELEM) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_TUPLE(elf,els) \
	BOOST_VMD_DETAIL_DATA_EQUAL_8(elf,els,BOOST_PP_TUPLE_SIZE,BOOST_PP_TUPLE_ELEM) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_TUPLE_D(d,elf,els) \
	BOOST_VMD_DETAIL_DATA_EQUAL_8_D(d,elf,els,BOOST_PP_TUPLE_SIZE,BOOST_PP_TUPLE_ELEM) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_IR(elf,els,vtype) \
	BOOST_PP_IIF \
		( \
		BOOST_VMD_DETAIL_EQUAL_TYPE(BOOST_VMD_TYPE_ARRAY,vtype), \
		BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_ARRAY, \
		BOOST_PP_IIF \
			( \
			BOOST_VMD_DETAIL_EQUAL_TYPE(BOOST_VMD_TYPE_SEQ,vtype), \
			BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_SEQ, \
			BOOST_PP_IIF \
				( \
				BOOST_VMD_DETAIL_EQUAL_TYPE(BOOST_VMD_TYPE_TUPLE,vtype), \
				BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_TUPLE, \
				BOOST_VMD_IDENTITY(0) \
				) \
			) \
		) \
	(elf,els) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_IR_D(d,elf,els,vtype) \
	BOOST_PP_IIF \
		( \
		BOOST_VMD_DETAIL_EQUAL_TYPE_D(d,BOOST_VMD_TYPE_ARRAY,vtype), \
		BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_ARRAY_D, \
		BOOST_PP_IIF \
			( \
			BOOST_VMD_DETAIL_EQUAL_TYPE_D(d,BOOST_VMD_TYPE_SEQ,vtype), \
			BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_SEQ_D, \
			BOOST_PP_IIF \
				( \
				BOOST_VMD_DETAIL_EQUAL_TYPE_D(d,BOOST_VMD_TYPE_TUPLE,vtype), \
				BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_TUPLE_D, \
				BOOST_VMD_IDENTITY(0) \
				) \
			) \
		) \
	(d,elf,els) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC(elf,els,vtype) \
	BOOST_VMD_IDENTITY_RESULT(BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_IR(elf,els,vtype)) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_D(d,elf,els,vtype) \
	BOOST_VMD_IDENTITY_RESULT(BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_IR_D(d,elf,els,vtype)) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_IR(elf,els,vtype) \
	BOOST_PP_IIF \
		( \
		BOOST_PP_BITAND \
			( \
			BOOST_VMD_DETAIL_EQUAL_TYPE(BOOST_VMD_TYPE(elf),vtype), \
			BOOST_VMD_DETAIL_EQUAL_TYPE(BOOST_VMD_TYPE(els),vtype) \
			), \
		BOOST_VMD_DETAIL_COMP_EQUAL_8_NC, \
		BOOST_VMD_IDENTITY(0) \
		) \
	(elf,els,vype) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_IR_D(d,elf,els,vtype) \
	BOOST_PP_IIF \
		( \
		BOOST_PP_BITAND \
			( \
			BOOST_VMD_DETAIL_EQUAL_TYPE_D(d,BOOST_VMD_TYPE_D(d,elf),vtype), \
			BOOST_VMD_DETAIL_EQUAL_TYPE_D(d,BOOST_VMD_TYPE_D(d,els),vtype) \
			), \
		BOOST_VMD_DETAIL_COMP_EQUAL_8_NC_D, \
		BOOST_VMD_IDENTITY(0) \
		) \
	(d,elf,els,vtype) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8(elf,els,vtype) \
	BOOST_VMD_IDENTITY_RESULT(BOOST_VMD_DETAIL_COMP_EQUAL_8_IR(elf,els,vtype)) \
/**/

#define BOOST_VMD_DETAIL_COMP_EQUAL_8_D(d,elf,els,vtype) \
	BOOST_VMD_IDENTITY_RESULT(BOOST_VMD_DETAIL_COMP_EQUAL_8_IR_D(d,elf,els,vtype)) \
/**/

#endif /* BOOST_VMD_DETAIL_COMP_EQUAL_8_HPP */
