#if !defined(BOOST_VMD_TUPLE_PROCESSING_HPP)
#define BOOST_VMD_TUPLE_PROCESSING_HPP

#include <boost/vmd/detail/setup.hpp>

#if BOOST_PP_VARIADICS

#define BOOST_VMD_GENERAL_TUPLE 0
#define BOOST_VMD_SPECIFIC_TUPLE 1

#endif /* BOOST_PP_VARIADICS */
#endif /* BOOST_VMD_TUPLE_PROCESSING_HPP */
