#if !defined(VMD_DETAIL_IS_TUPLE_BEGIN_HPP)
#define VMD_DETAIL_IS_TUPLE_BEGIN_HPP

#include <boost/variadic_macro_data/detail/vmd_detail_setup.hpp>

#if BOOST_VMD_VARIADICS

#if BOOST_VMD_MSVC

#include <boost/preprocessor/facilities/empty.hpp>

#define VMD_DETAIL_VD_IS_BEGIN_PARENS_CAT(a, b) VMD_DETAIL_VD_IS_BEGIN_PARENS_CAT_I(a, b)
#define VMD_DETAIL_VD_IS_BEGIN_PARENS_CAT_I(a, b) VMD_DETAIL_VD_IS_BEGIN_PARENS_CAT_II(a ## b)
#define VMD_DETAIL_VD_IS_BEGIN_PARENS_CAT_II(res) res

#define VMD_DETAIL_IS_BEGIN_PARENS_SPLIT(i, ...) \
    VMD_DETAIL_VD_IS_BEGIN_PARENS_CAT(VMD_DETAIL_IS_BEGIN_PARENS_PRIMITIVE_CAT(VMD_DETAIL_IS_BEGIN_PARENS_SPLIT_,i)(__VA_ARGS__),BOOST_PP_EMPTY()) \
/**/

#define VMD_DETAIL_IS_BEGIN_PARENS_IS_VARIADIC_C(...) 1 1

#else

#define VMD_DETAIL_IS_BEGIN_PARENS_SPLIT(i, ...) \
    VMD_DETAIL_IS_BEGIN_PARENS_PRIMITIVE_CAT(VMD_DETAIL_IS_BEGIN_PARENS_SPLIT_,i)(__VA_ARGS__) \
/**/

#define VMD_DETAIL_IS_BEGIN_PARENS_IS_VARIADIC_C(...) 1

#endif /* BOOST_VMD_MSVC */

#define VMD_DETAIL_IS_BEGIN_PARENS_SPLIT_0(a, ...) a
#define VMD_DETAIL_IS_BEGIN_PARENS_SPLIT_1(a, ...) __VA_ARGS__

#define VMD_DETAIL_IS_BEGIN_PARENS_CAT(a, ...) VMD_DETAIL_IS_BEGIN_PARENS_PRIMITIVE_CAT(a,__VA_ARGS__)
#define VMD_DETAIL_IS_BEGIN_PARENS_PRIMITIVE_CAT(a, ...) a ## __VA_ARGS__

#define VMD_DETAIL_IS_BEGIN_PARENS_IS_VARIADIC_R_1 1,
#define VMD_DETAIL_IS_BEGIN_PARENS_IS_VARIADIC_R_VMD_DETAIL_IS_BEGIN_PARENS_IS_VARIADIC_C 0,

#endif /* BOOST_VMD_VARIADICS */
#endif /* VMD_DETAIL_IS_TUPLE_BEGIN_HPP */
