#if !defined(VMD_DETAIL_ASSERT_IS_ARRAY_COMMON_HPP)
#define VMD_DETAIL_ASSERT_IS_ARRAY_COMMON_HPP

#include <boost/variadic_macro_data/detail/vmd_detail_setup.hpp>

#if BOOST_VMD_VARIADICS

#if BOOST_VMD_ASSERT_DATA

#include <boost/preprocessor/cat.hpp>
#include <boost/variadic_macro_data/vmd_is_empty.hpp>

#if BOOST_VMD_MSVC

#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/debug/assert.hpp>
#include <boost/preprocessor/facilities/empty.hpp>

#define VMD_DETAIL_ASSERT_IS_ARRAY_VC_CHECK_RETURN_FAILURE(x) \
    BOOST_PP_ASSERT \
      ( \
      x \
      ) \
    BOOST_PP_IIF \
      ( \
      x, \
      BOOST_PP_EMPTY, \
      VMD_DETAIL_ASSERT_IS_ARRAY_VC_GEN_ERROR_OUTPUT \
      ) \
    () \
/**/

#define VMD_DETAIL_ASSERT_IS_ARRAY_VC_GEN_ERROR_OUTPUT() \
    typedef char BOOST_VMD_IS_ARRAY_ASSERT_ERROR[-1]; \
/**/

#define VMD_DETAIL_ASSERT_IS_ARRAY_GEN_ZERO(x) 0

#endif /* BOOST_VMD_MSVC */

#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM(x) BOOST_VMD_IS_EMPTY(BOOST_PP_CAT(VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_, x))
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_1
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_2
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_3
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_4
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_5
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_6
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_7
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_8
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_9
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_10
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_11
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_12
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_13
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_14
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_15
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_16
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_17
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_18
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_19
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_20
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_21
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_22
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_23
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_24
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_25
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_26
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_27
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_28
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_29
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_30
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_31
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_32
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_33
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_34
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_35
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_36
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_37
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_38
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_39
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_40
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_41
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_42
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_43
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_44
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_45
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_46
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_47
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_48
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_49
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_50
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_51
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_52
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_53
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_54
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_55
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_56
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_57
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_58
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_59
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_60
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_61
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_62
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_63
#define VMD_DETAIL_ASSERT_IS_ARRAY_NUM_HELPER_64

#endif /* BOOST_VMD_ASSERT_DATA */
#endif /* BOOST_VMD_VARIADICS */
#endif /* VMD_DETAIL_ASSERT_ASSERT_IS_ARRAY_COMMON_HPP */
