#if !defined(BOOST_VMD_DETAIL_SPLIT_NUMBER_HPP)
#define BOOST_VMD_DETAIL_SPLIT_NUMBER_HPP

#include <boost/vmd/elem.hpp>
#include <boost/vmd/detail/elem_split.hpp>

#define BOOST_VMD_DETAIL_ELEM_SPLIT_NUMBER(elem,...) \
	BOOST_VMD_DETAIL_ELEM_SPLIT(BOOST_VMD_ELEM(elem,__VA_ARGS__,BOOST_VMD_RETURN_TYPE_TUPLE),BOOST_VMD_TYPE_NUMBER) \
/**/

#define BOOST_VMD_DETAIL_ELEM_SPLIT_NUMBER_D(d,elem,...) \
	BOOST_VMD_DETAIL_ELEM_SPLIT_D(d,BOOST_VMD_ELEM_D(d,elem,__VA_ARGS__,BOOST_VMD_RETURN_TYPE_TUPLE),BOOST_VMD_TYPE_NUMBER) \
/**/

#endif /* BOOST_VMD_DETAIL_SPLIT_NUMBER_HPP */
