#if !defined(BOOST_VMD_DETAIL_AFTER_IDENTIFIER_HPP)
#define BOOST_VMD_DETAIL_AFTER_IDENTIFIER_HPP

#include <boost/vmd/detail/elem_identifier.hpp>
#include <boost/vmd/detail/modifiers.hpp>

#define BOOST_VMD_DETAIL_ELEM_AFTER_IDENTIFIER(elem,...) \
	BOOST_VMD_DETAIL_ELEM_IDENTIFIER(elem,__VA_ARGS__,BOOST_VMD_RETURN_ONLY_AFTER) \
/**/

#define BOOST_VMD_DETAIL_ELEM_AFTER_IDENTIFIER_D(d,elem,...) \
	BOOST_VMD_DETAIL_ELEM_IDENTIFIER_D(d,elem,__VA_ARGS__,BOOST_VMD_RETURN_ONLY_AFTER) \
/**/

#endif /* BOOST_VMD_DETAIL_AFTER_IDENTIFIER_HPP */
