#if !defined(BOOST_VMD_DETAIL_IS_FROM_HPP)
#define BOOST_VMD_DETAIL_IS_FROM_HPP

#include <boost/vmd/detail/match_identifier.hpp>

#define BOOST_VMD_REGISTER_BOOST_VMD_RETURN_GENERAL_TUPLE_TYPE (BOOST_VMD_RETURN_GENERAL_TUPLE_TYPE)
#define BOOST_VMD_REGISTER_BOOST_VMD_RETURN_EXACT_TYPE (BOOST_VMD_RETURN_EXACT_TYPE)
#define BOOST_VMD_REGISTER_BOOST_VMD_RETURN_NO_TYPE (BOOST_VMD_RETURN_NO_TYPE)
#define BOOST_VMD_REGISTER_BOOST_VMD_RETURN_AFTER (BOOST_VMD_RETURN_AFTER)
#define BOOST_VMD_REGISTER_BOOST_VMD_RETURN_NO_AFTER (BOOST_VMD_RETURN_NO_AFTER)
#define BOOST_VMD_REGISTER_BOOST_VMD_SPECIFIC_ARRAY (BOOST_VMD_SPECIFIC_ARRAY)
#define BOOST_VMD_REGISTER_BOOST_VMD_SPECIFIC_LIST  (BOOST_VMD_SPECIFIC_LIST)

#define BOOST_VMD_DETECT_BOOST_VMD_RETURN_GENERAL_TUPLE_TYPE_BOOST_VMD_RETURN_GENERAL_TUPLE_TYPE
#define BOOST_VMD_DETECT_BOOST_VMD_RETURN_EXACT_TYPE_BOOST_VMD_RETURN_EXACT_TYPE
#define BOOST_VMD_DETECT_BOOST_VMD_RETURN_NO_TYPE_BOOST_VMD_RETURN_NO_TYPE
#define BOOST_VMD_DETECT_BOOST_VMD_RETURN_AFTER_BOOST_VMD_RETURN_AFTER
#define BOOST_VMD_DETECT_BOOST_VMD_RETURN_NO_AFTER_BOOST_VMD_RETURN_NO_AFTER
#define BOOST_VMD_DETECT_BOOST_VMD_SPECIFIC_ARRAY_BOOST_VMD_SPECIFIC_ARRAY
#define BOOST_VMD_DETECT_BOOST_VMD_SPECIFIC_LIST_BOOST_VMD_SPECIFIC_LIST

#define BOOST_VMD_DETAIL_IS_RETURN_GENERAL_TUPLE_TYPE(id) \
	BOOST_VMD_DETAIL_MATCH_SINGLE_IDENTIFIER(id,BOOST_VMD_RETURN_GENERAL_TUPLE_TYPE) \
/**/

#define BOOST_VMD_DETAIL_IS_RETURN_EXACT_TYPE(id) \
	BOOST_VMD_DETAIL_MATCH_SINGLE_IDENTIFIER(id,BOOST_VMD_RETURN_EXACT_TYPE) \
/**/

#define BOOST_VMD_DETAIL_IS_RETURN_NO_TYPE(id) \
	BOOST_VMD_DETAIL_MATCH_SINGLE_IDENTIFIER(id,BOOST_VMD_RETURN_NO_TYPE) \
/**/

#define BOOST_VMD_DETAIL_IS_RETURN_AFTER(id) \
	BOOST_VMD_DETAIL_MATCH_SINGLE_IDENTIFIER(id,BOOST_VMD_RETURN_AFTER) \
/**/

#define BOOST_VMD_DETAIL_IS_RETURN_NO_AFTER(id) \
	BOOST_VMD_DETAIL_MATCH_SINGLE_IDENTIFIER(id,BOOST_VMD_RETURN_NO_AFTER) \
/**/

#define BOOST_VMD_DETAIL_IS_SPECIFIC_ARRAY(id) \
	BOOST_VMD_DETAIL_MATCH_SINGLE_IDENTIFIER(id,BOOST_VMD_SPECIFIC_ARRAY) \
/**/

#define BOOST_VMD_DETAIL_IS_SPECIFIC_LIST(id) \
	BOOST_VMD_DETAIL_MATCH_SINGLE_IDENTIFIER(id,BOOST_VMD_SPECIFIC_LIST) \
/**/

#endif /* BOOST_VMD_DETAIL_IS_FROM_HPP */
