#if !defined(BOOST_VMD_DETAIL_NIL_REGISTRATION_HPP)
#define BOOST_VMD_DETAIL_NIL_REGISTRATION_HPP

#define BOOST_VMD_REGISTER_BOOST_PP_NIL (BOOST_PP_NIL)
#define BOOST_VMD_DETECT_BOOST_PP_NIL_BOOST_PP_NIL

#endif /* BOOST_VMD_DETAIL_NIL_REGISTRATION_HPP */
